---
abstract: 'Hierarchy-wide accumulation of list and hash results'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Inherited
provides:
  Data::Inherited:
    file: lib/Data/Inherited.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  NEXT: 0.64
  Scalar::Util: 0
  Test::More: 0.88
  constant: 0
  overload: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Inherited
  homepage: http://search.cpan.org/dist/Data-Inherited/
  repository: http://github.com/hanekomu/Data-Inherited
version: 1.100860
