--- 
abstract: hierarchy-wide accumulation of list and hash results
author: Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Inherited
no_index: 
  directory: 
    - inc
    - t
version: 1.02
